name = "OffShellReconstruct"
uuid = "6d11e18a-007c-4175-9923-7774072c081d"
authors = ["Ali <a_eghrari@yahoo.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
